experiment_id: "03"

## Simulation parameters
simulation_id: [0, 100, 1]  # [start_id, end_id, step] - excludes the end_id.
integration_step_size: 1.0  # ms - time-step-size to be used in the differential euqation integration scheme.
simulation_duration: 11000  # ms - duration for which the models should be evolved.
initial_transient: 1000  # ms - transient to be removed from data.

## Model parameters
# network parameters
nx: 30  # number of regions along x-dimension
ny: 30  # number of regions along y-dimension
x_extent: 140  # mm, extent of x-dimension
y_extent: 140  # mm, extent of y-dimension

boundary_k_ring: -1

coupling_strength: 0.01  # global scaling of all connections
conduction_speed: 3.0  # mm/ms conduction speed between nodes
connection_strength_scaling: 10  # mm - scaling factor for distance-dependent connection strength
connection_probability_scale: 17  # scale parameter for distance-dependent connection probability

instrength_gradient_offset: 4  # offset of in-strength gradient field.
instrength_gradient_scaling: 2  # scale the min-max normalized gradient
sink_pos: [40, 40]  # mm - sink position (gaussian)
source_pos: [100, 100]  # mm - source position (gaussian)
singularity_width: 300  # mm^2 - width of sink and source (normal variance)

# kuramoto parameters
intrinsic_frequency_mean: 10.  # Hz - Kuramoto oscillator intrinsic frequency mean
intrinsic_frequency_standard_deviation: 0.0  # Hz - Kuramoto oscillator intrinsic frequency standard deviation

# parameter to explore
intrinsic_frequency_gradient_scaling: [0, 1.5, 31]  # scaling of intrinsic frequency


## Data
data_path: "data/"
save_path: "03_simulations"