# analysis parameters
downsampling_factor: 5  # a.u. downsample the time steps by this factor

# bandpass filter parameters
f_low: 5  # Hz
f_high: 15  # Hz

## detection parameters
number_of_permutations: 1000  # permutations for random surrogate data tests
significance_level: 0.01  # significance level for surrogate data tests

data_path: "data/"