experiment_id: '51'

## Simulation parameters
simulation_id: [0, 100, 1]  # [start_id, end_id, step] - excludes the end_id.
integration_step_size: 1.0  # ms - time-step-size to be used in the differential equation integration scheme.
simulation_duration: 11000  # ms - duration for which the models should be evolved.
initial_transient: 1000  # ms - transient to be removed from data.

## Model parameters
# network parameters
coupling_strength: 0.00001  # global scaling of all connections
conduction_speed: 3.0  # mm/ms conduction speed between nodes

boundary_k_ring: -1

intrinsic_frequency_mean: 10.  # Hz - Kuramoto oscillator intrinsic frequency mean
intrinsic_frequency_standard_deviation: 1.0  # Hz - Kuramoto oscillator intrinsic frequency standard deviation

## Data
data_path: "data/"  # for singularity/docker container
weights_path: "connectomes/Schaefer2018_HCP_S900/avg_weights.npy"
lengths_path: "connectomes/Schaefer2018_HCP_S900/avg_lengths.npy"
labels_path: "connectomes/Schaefer2018_HCP_S900/labels.npy"
positions_path: "connectomes/Schaefer2018_HCP_S900/positions.npy"
instrength_path: "connectomes/Schaefer2018_HCP_S900/instrength.npy"
